# Classic matrix multiplication

In [10]:
def mul(m1, m2, sz):
    r = 0
    for i in range(sz):
        for j in range(sz):
            for k in range(sz):
                r += m1[i][k] * m2[k][j]
    return r

In [11]:
import numpy as np

size = 5

m1 = np.random.randint(-10, 10, (size, size))
m2 = np.random.randint(-10, 10, (size, size))
print(m1)
print(m2)

[[ -3  -3  -7   2   8]
 [  6   7  -2   1   1]
 [  4   0 -10  -8  -3]
 [ -5  -4  -2  -8  -8]
 [  2   2   0   3   5]]


In [12]:
print(mul(m1, m2, size))

677
